### ISSUE TITLE
[Question] About dataset random ordering code

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#1099]
How to reproduce the behaviour
---------
As we [talked](https://github.com/doccano/doccano/pull/1072/files#r531214151), this code:

https://github.com/doccano/doccano/blob/6be605289005ec715f9c9e54d91ca268f8641aa2/app/api/views.py#L173-L177

is not truely random. But how do these lines work? I don't understand :)

> And why does this patch work? We only replace `self.request.user.id` with `f(self.request.user.id)`, where `f` isn't random function. Yeah? `value = random.randrange(2, 20)` will be the the same for the same seed (`self.request.user.id`), woudn't it be?

How does this work, exactly? Why does this shuffle at all?

Thanks!

Your Environment
---------

*   Operating System: Ubuntu 18.04.4 LTS
*   Python Version Used: system Python is 3.6.9
*   When you install doccano: 6be605289005ec715f9c9e54d91ca268f8641aa2
*   How did you install doccano (Heroku button etc): Docker Compose (production)

**Comment by fjen** [comment]
It's a "deterministic shuffle" based on the user id. An additional field `sort_id` is added to the documents on-the-fly, initialized with `id mod value` and then used for sorting. In the end you get every n'th document first, then every n+1. 

Example:
document ids: 1..10
random value: 3
order: 3, 6, 9, 1, 4, 7, 10, 2, 5, 8

**Comment by kuraga** [comment]
@fjen , thanks!

1. Only unannotated documents' ids are sorted. Correct?

2. Set of ids aren't unique for users. Correct?

**Comment by fjen** [comment]
1. This has nothing to do with documents being annotated or not. The queryset is defined over all documents of one project.
2. The documents ids are not based on the user. Order after shuffle different for every user but the same user always receives the same ordering. I hope this answeres your question, otherwise you need to be more specific.

**Comment by kuraga** [comment]
@fjen I just know an issue: sometimes user sees an already annotated document.

**Comment by fjen** [comment]
I think that issue should be fixed with the current code. The problem was, that ordering was performed on `sort_id` only which isn't/wasn't unique. By adding `id` as a second order criteria a stable ordering is achieved. The rest of the code incl. `random` is just for better randomization. e.g. user with id 1 got no shuffling before.

**Comment by kuraga** [comment]
@fjen Aha, now I see the mechanics. My questions were pretty silly.

I understand everything except why adding `id` to sorting solves the issue. 

And I don't understand why it's difficult to get 20 pseudo-random numbers :)

**Comment by fjen** [comment]
`sort_id` is defined as `id modulo X` means the result are numbers from 0 to X-1. This causes multiple documents to have the same `sort_id`. Documents with id 1 and 6 have the same sort_id if X=5. Sorting on this only is not deterministic. 

The code creates **one** random number in range 2..19 for X depending on the user id. Not 20 numbers.

**Comment by kuraga** [comment]
> Sorting on this only is not deterministic.

Yes. But it doesn't solve:

> sometimes user sees (UPD: saw before #1072, I don't know current state) an already annotated document.

> The code creates one random number in range 2..19 for X depending on the user id. Not 20 numbers.

I know. I talked about mechanism "on Annotation page, we get 20 documents per batch." Every 21 document browser gets new batch. I think we have an ability get 20 true pseudo-random number per request.

So, before #1072: user A gets a batch of 20 documents. User B comes a minute later and gets his 20 documents. They might intersect.

Was this fixed by #1072? As I see, no.

**Comment by fjen** [comment]
The randomized order option does not filter for non-annotated documents. This would be the purpose of another option, which does not exist currently.

**Comment by kuraga** [comment]
UI doesn't filter, too. It just shows next 20 documents.

Is this code used, isn't it?

**Comment by kuraga** [comment]
@fjen ,

UI doesn't filter, too. It just shows next 20 documents.

Is this code used, isn't it?
